version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8000:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0.21
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
