version: '3.8'
services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: 'python main.py'
  #   ports:
  #     - 8000:5000
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db

  db:
    image: mysql/mysql-server:8.0.21
    restart: always
    environment:
      MYSQL_DATABASE: data-bites
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
