SET foreign_key_checks = 0;
DROP TABLE IF EXISTS Ambience;
DROP TABLE IF EXISTS BestNights;
DROP TABLE IF EXISTS BusinessParking;
DROP TABLE IF EXISTS DietaryRestrictions;
DROP TABLE IF EXISTS GoodForMeal;
DROP TABLE IF EXISTS HairSpecializesIn;
DROP TABLE IF EXISTS Music;
DROP TABLE IF EXISTS Attributes;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Business_Hours;
DROP TABLE IF EXISTS Business;
DROP TABLE IF EXISTS Checkin;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Tips;
DROP TABLE IF EXISTS UserFriends;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS UserElite;
SET foreign_key_checks = 1;

CREATE TABLE Business (
    business_id char(22) NOT NULL,
    name varchar(70) NOT NULL,
	-- max is 64
    address varchar(110) NOT NULL,
	-- max is 107
    city varchar(40) NOT NULL,
	-- max is 35
    state char(2) NOT NULL, 
	-- max is 2; there is one incorrect entry with 3 letters
    postal_code char(7) NOT NULL,
	-- max is 7 with few postal-codes missing all values (missing last number)
    latitude decimal(9,6) NOT NULL,
    longitude decimal(9,6) NOT NULL,
    stars float,
    review_count int,
    is_open BOOLEAN
);

CREATE TABLE User (
    user_id char(22) NOT NULL,
    name varchar(35),
	-- max is 32
    review_count int,
    yelping_since datetime,
    useful int,
    funny int,
    cool int, 
    fans int,
    average_stars int,
    compliment_hot int,
    compliment_more int,
    compliment_profile int,
    compliment_cute int,
    compliment_list int,
    compliment_note int,
    compliment_plain int,
    compliment_cool int,
    compliment_funny int,
    compliment_writer int,
    compliment_photos int
);

CREATE TABLE UserElite(
    user_id char(22) NOT NULL,
    elite int(4) NOT NULL
    -- elite is the year i.e. 2012; 2015
);

CREATE TABLE UserFriends(
    user_id char(22) NOT NULL,
    friend_id char(22) NOT NULL
);

CREATE TABLE Checkin(
    business_id char(22) NOT NULL,
    date datetime NOT NULL
);

CREATE TABLE Tips (
    business_id char(22) NOT NULL,
    user_id char(22) NOT NULL,
    text varchar(500),
    -- max is 500
    date datetime,
    compliment_count int
);

CREATE TABLE Reviews (
    review_id char(22) NOT NULL,
    user_id char(22) NOT NULL,
    business_id char(22) NOT NULL,
    stars int,
    useful int, 
    funny int,
    cool int,
    text varchar(5000),
    -- max is 5000
    date datetime
);

CREATE TABLE Business_Hours (
    business_id char(11) NOT NULL,
    Monday char(11),
    Tuesday char(11),
    Wednesday char(11),
    Thursday char(11),
    Friday char(11),
    Saturday char(11),
    Sunday char(11)
	-- max is 11
	-- i.e. 11:0-7:0
	-- Maybe alter opening / closing time for each day
 );

CREATE TABLE Attributes (
    business_id char(22) NOT NULL,
    RestaurantsTableService BOOLEAN,
    -- Booleans include true, false and none...
    WiFi char(7),
    -- values like 'no', 'free', 'paid'; max is 7
	-- Alter table to enum type
    BikeParking BOOLEAN,
    BusinessAcceptsCreditCards BOOLEAN,
    RestaurantsReservations BOOLEAN,
    WheelchairAccessible BOOLEAN,
    Caters BOOLEAN,
    OutdoorSeating BOOLEAN,
    RestaurantsGoodForGroups BOOLEAN,
    HappyHour BOOLEAN,
    BusinessAcceptsBitcoin BOOLEAN,
    RestaurantsPriceRange2 int,
    HasTV BOOLEAN,
    Alcohol char(16),
    -- values like beer_and_wine, none, full_bar; max is 16
    DogsAllowed BOOLEAN,
    RestaurantsTakeOut BOOLEAN,
    NoiseLevel char(12),
	-- max is 12
    RestaurantsAttire char(9),
	-- max is 9
    RestaurantsDelivery BOOLEAN,
    -- includes T_F_None...
    GoodForKids BOOLEAN,
    ByAppointmentOnly BOOLEAN,
    AcceptsInsurance BOOLEAN,
    GoodForDancing BOOLEAN,
    BYOB BOOLEAN,
    CoatCheck BOOLEAN,
    Smoking char(10),
    -- yes, no, outdoor; max is 10
    DriveThru BOOLEAN,
    BYOBCorkage BOOLEAN,
    Corkage BOOLEAN,
    RestaurantsCounterService BOOLEAN,
    AgesAllowed char(10),
	-- max is 10
    Open24Hours BOOLEAN
);

CREATE TABLE Ambience (
    business_id char(22) NOT NULL,
    touristy BOOLEAN,
    hipster BOOLEAN,
    romantic BOOLEAN,
    divey BOOLEAN,
    intimate BOOLEAN,
    trendy BOOLEAN,
    upscale BOOLEAN,
    classy BOOLEAN,
    casual BOOLEAN
);

CREATE TABLE BestNights (
    business_id char(22) NOT NULL,
    monday BOOLEAN,
    tuesday BOOLEAN,
    friday BOOLEAN,
    wednesday BOOLEAN,
    thursday BOOLEAN,
    sunday BOOLEAN,
    saturday BOOLEAN
);

CREATE TABLE BusinessParking (
    business_id char(22) NOT NULL,
    garage BOOLEAN,
    street BOOLEAN,
    validated BOOLEAN,
    lot BOOLEAN,
    valet BOOLEAN
);

CREATE TABLE DietaryRestrictions (
    business_id char(22) NOT NULL,
    dairy_free BOOLEAN,
    gluten_free BOOLEAN,
    vegan BOOLEAN,
    kosher BOOLEAN,
    halal BOOLEAN,
    soy_free BOOLEAN,
    vegetarian BOOLEAN
);

CREATE TABLE GoodForMeal (
    business_id char(22) NOT NULL,
    dessert BOOLEAN,
    latenight BOOLEAN,
    lunch BOOLEAN,
    dinner BOOLEAN,
    brunch BOOLEAN,
    breakfast BOOLEAN
);

CREATE TABLE HairSpecializesIn (
    business_id char(22) NOT NULL,
    straightperms BOOLEAN,
    coloring BOOLEAN,
    extensions BOOLEAN,
    africanamerican BOOLEAN,
    curly BOOLEAN,
    kids BOOLEAN,
    perms BOOLEAN,
    asian BOOLEAN
);

CREATE TABLE Music (
    business_id char(22) NOT NULL,
    dj BOOLEAN,
    background_music BOOLEAN,
    no_music BOOLEAN,
    jukebox BOOLEAN,
    live BOOLEAN,
    video BOOLEAN,
    karaoke BOOLEAN
);

-- Change this 
-- BusinessA 3dprinting, atv
-- businessB atv, active_life, acupuncture
-- col 1= business; col enum_string
-- string: "atv, 3d"

CREATE TABLE Categories (
	business_id char(22) NOT NULL,
	and_Probates BOOLEAN,
	3D_Printing BOOLEAN,
	ATV_Rentals_Tours BOOLEAN,
	Acai_Bowls BOOLEAN,
	Accessories BOOLEAN,
	Accountants BOOLEAN,
	Acne_Treatment BOOLEAN,
	Active_Life BOOLEAN,
	Acupuncture BOOLEAN,
	Addiction_Medicine BOOLEAN,
	Adoption_Services BOOLEAN,
	Adult BOOLEAN,
	Adult_Education BOOLEAN,
	Adult_Entertainment BOOLEAN,
	Advertising BOOLEAN,
	Aerial_Fitness BOOLEAN,
	Aerial_Tours BOOLEAN,
	Aestheticians BOOLEAN,
	Afghan BOOLEAN,
	African BOOLEAN,
	Air_Duct_Cleaning BOOLEAN,
	Aircraft_Dealers BOOLEAN,
	Aircraft_Repairs BOOLEAN,
	Airlines BOOLEAN,
	Airport_Lounges BOOLEAN,
	Airport_Shuttles BOOLEAN,
	Airport_Terminals BOOLEAN,
	Airports BOOLEAN,
	Airsoft BOOLEAN,
	Allergists BOOLEAN,
	Alternative_Medicine BOOLEAN,
	Amateur_Sports_Teams BOOLEAN,
	American_New BOOLEAN,
	American_Traditional BOOLEAN,
	Amusement_Parks BOOLEAN,
	Anesthesiologists BOOLEAN,
	Animal_Assisted_Therapy BOOLEAN,
	Animal_Physical_Therapy BOOLEAN,
	Animal_Shelters BOOLEAN,
	Antiques BOOLEAN,
	Apartment_Agents BOOLEAN,
	Apartments BOOLEAN,
	Appliances BOOLEAN,
	Appliances_and_Repair BOOLEAN,
	Appraisal_Services BOOLEAN,
	Aquarium_Services BOOLEAN,
	Aquariums BOOLEAN,
	Arabian BOOLEAN,
	Arcades BOOLEAN,
	Archery BOOLEAN,
	Architects BOOLEAN,
	Architectural_Tours BOOLEAN,
	Argentine BOOLEAN,
	Armenian BOOLEAN,
	Art_Classes BOOLEAN,
	Art_Consultants BOOLEAN,
	Art_Galleries BOOLEAN,
	Art_Installation BOOLEAN,
	Art_Museums BOOLEAN,
	Art_Restoration BOOLEAN,
	Art_Schools BOOLEAN,
	Art_Space_Rentals BOOLEAN,
	Art_Supplies BOOLEAN,
	Art_Tours BOOLEAN,
	Artificial_Turf BOOLEAN,
	Arts_and_Crafts BOOLEAN,
	Arts_and_Entertainment BOOLEAN,
	Asian_Fusion BOOLEAN,
	Assisted_Living_Facilities BOOLEAN,
	Astrologers BOOLEAN,
	Attraction_Farms BOOLEAN,
	Auction_Houses BOOLEAN,
	Audio_Visual_Equipment_Rental BOOLEAN,
	Audiologist BOOLEAN,
	Australian BOOLEAN,
	Austrian BOOLEAN,
	Auto_Customization BOOLEAN,
	Auto_Detailing BOOLEAN,
	Auto_Electric_Services BOOLEAN,
	Auto_Glass_Services BOOLEAN,
	Auto_Insurance BOOLEAN,
	Auto_Loan_Providers BOOLEAN,
	Auto_Parts_and_Supplies BOOLEAN,
	Auto_Repair BOOLEAN,
	Auto_Security BOOLEAN,
	Auto_Upholstery BOOLEAN,
	Automotive BOOLEAN,
	Awnings BOOLEAN,
	Axe_Throwing BOOLEAN,
	Ayurveda BOOLEAN,
	Baby_Gear_and_Furniture BOOLEAN,
	Backflow_Services BOOLEAN,
	Badminton BOOLEAN,
	Bagels BOOLEAN,
	Bail_Bondsmen BOOLEAN,
	Bakeries BOOLEAN,
	Balloon_Services BOOLEAN,
	Bangladeshi BOOLEAN,
	Bankruptcy_Law BOOLEAN,
	Banks_and_Credit_Unions BOOLEAN,
	Bar_Crawl BOOLEAN,
	Barbeque BOOLEAN,
	Barbers BOOLEAN,
	Barre_Classes BOOLEAN,
	Bars BOOLEAN,
	Bartenders BOOLEAN,
	Bartending_Schools BOOLEAN,
	Baseball_Fields BOOLEAN,
	Basketball_Courts BOOLEAN,
	Basque BOOLEAN,
	Battery_Stores BOOLEAN,
	Batting_Cages BOOLEAN,
	Beach_Equipment_Rentals BOOLEAN,
	Beaches BOOLEAN,
	Beauty_and_Spas BOOLEAN,
	Bed_and_Breakfast BOOLEAN,
	Beer BOOLEAN,
	Beer_Bar BOOLEAN,
	Beer_Garden BOOLEAN,
	Beer_Gardens BOOLEAN,
	Beer_Tours BOOLEAN,
	Behavior_Analysts BOOLEAN,
	Belgian BOOLEAN,
	Bespoke_Clothing BOOLEAN,
	Beverage_Store BOOLEAN,
	Bicycles BOOLEAN,
	Bike_Parking BOOLEAN,
	Bike_Rentals BOOLEAN,
	Bike_Repair BOOLEAN,
	Bike_Repair_Maintenance BOOLEAN,
	Bike_Sharing BOOLEAN,
	Bike_Shop BOOLEAN,
	Bike_tours BOOLEAN,
	Bikes BOOLEAN,
	Billing_Services BOOLEAN,
	Bingo_Halls BOOLEAN,
	Biohazard_Cleanup BOOLEAN,
	Bird_Shops BOOLEAN,
	Bistros BOOLEAN,
	Blood_and_Plasma_Donation_Centers BOOLEAN,
	Blow_Dry_Out_Services BOOLEAN,
	Boat_Charters BOOLEAN,
	Boat_Dealers BOOLEAN,
	Boat_Parts_and_Supplies BOOLEAN,
	Boat_Repair BOOLEAN,
	Boat_Tours BOOLEAN,
	Boating BOOLEAN,
	Bocce_Ball BOOLEAN,
	Body_Contouring BOOLEAN,
	Body_Shops BOOLEAN,
	Bookbinding BOOLEAN,
	Bookkeepers BOOLEAN,
	Books BOOLEAN,
	Bookstores BOOLEAN,
	Boot_Camps BOOLEAN,
	Botanical_Gardens BOOLEAN,
	Boudoir_Photography BOOLEAN,
	Bounce_House_Rentals BOOLEAN,
	Bowling BOOLEAN,
	Boxing BOOLEAN,
	Brasseries BOOLEAN,
	Brazilian BOOLEAN,
	Brazilian_Jiu_jitsu BOOLEAN,
	Breakfast_and_Brunch BOOLEAN,
	Breweries BOOLEAN,
	Brewing_Supplies BOOLEAN,
	Brewpubs BOOLEAN,
	Bridal BOOLEAN,
	British BOOLEAN,
	Bubble_Soccer BOOLEAN,
	Bubble_Tea BOOLEAN,
	Buddhist_Temples BOOLEAN,
	Buffets BOOLEAN,
	Building_Supplies BOOLEAN,
	Bulgarian BOOLEAN,
	Burgers BOOLEAN,
	Burmese BOOLEAN,
	Bus_Rental BOOLEAN,
	Bus_Stations BOOLEAN,
	Bus_Tours BOOLEAN,
	Buses BOOLEAN,
	Business_Consulting BOOLEAN,
	Business_Financing BOOLEAN,
	Business_Law BOOLEAN,
	Butcher BOOLEAN,
	CPR_Classes BOOLEAN,
	CSA BOOLEAN,
	Cabaret BOOLEAN,
	Cabinetry BOOLEAN,
	Cable_Cars BOOLEAN,
	Cafes BOOLEAN,
	Cafeteria BOOLEAN,
	Cajun_Creole BOOLEAN,
	Calabrian BOOLEAN,
	Calligraphy BOOLEAN,
	Cambodian BOOLEAN,
	Campgrounds BOOLEAN,
	Canadian_New BOOLEAN,
	Candle_Stores BOOLEAN,
	Candy_Stores BOOLEAN,
	Cannabis_Clinics BOOLEAN,
	Cannabis_Collective BOOLEAN,
	Cannabis_Dispensaries BOOLEAN,
	Cannabis_Tours BOOLEAN,
	Canteen BOOLEAN,
	Cantonese BOOLEAN,
	Car_Auctions BOOLEAN,
	Car_Brokers BOOLEAN,
	Car_Buyers BOOLEAN,
	Car_Dealers BOOLEAN,
	Car_Inspectors BOOLEAN,
	Car_Rental BOOLEAN,
	Car_Share_Services BOOLEAN,
	Car_Stereo_Installation BOOLEAN,
	Car_Wash BOOLEAN,
	Car_Window_Tinting BOOLEAN,
	Cardio_Classes BOOLEAN,
	Cardiologists BOOLEAN,
	Cards_and_Stationery BOOLEAN,
	Career_Counseling BOOLEAN,
	Caribbean BOOLEAN,
	Caricatures BOOLEAN,
	Carousels BOOLEAN,
	Carpenters BOOLEAN,
	Carpet_Cleaning BOOLEAN,
	Carpet_Dyeing BOOLEAN,
	Carpet_Installation BOOLEAN,
	Carpeting BOOLEAN,
	Casinos BOOLEAN,
	Castles BOOLEAN,
	Catalan BOOLEAN,
	Caterers BOOLEAN,
	Challenge_Courses BOOLEAN,
	Champagne_Bars BOOLEAN,
	Check_Cashing_Pay_day_Loans BOOLEAN,
	Cheerleading BOOLEAN,
	Cheese_Shops BOOLEAN,
	Cheese_Tasting_Classes BOOLEAN,
	Cheesesteaks BOOLEAN,
	Chicken_Shop BOOLEAN,
	Chicken_Wings BOOLEAN,
	Child_Care_and_Day_Care BOOLEAN,
	Childbirth_Education BOOLEAN,
	Childproofing BOOLEAN,
	Childrens_Clothing BOOLEAN,
	Childrens_Museums BOOLEAN,
	Chimney_Sweeps BOOLEAN,
	Chinese BOOLEAN,
	Chinese_Martial_Arts BOOLEAN,
	Chiropractors BOOLEAN,
	Chocolatiers_and_Shops BOOLEAN,
	Christmas_Markets BOOLEAN,
	Christmas_Trees BOOLEAN,
	Churches BOOLEAN,
	Churros BOOLEAN,
	Cideries BOOLEAN,
	Cigar_Bars BOOLEAN,
	Cinema BOOLEAN,
	Circuit_Training_Gyms BOOLEAN,
	Circus_Schools BOOLEAN,
	Civic_Center BOOLEAN,
	Climbing BOOLEAN,
	Clock_Repair BOOLEAN,
	Clothing_Rental BOOLEAN,
	Clowns BOOLEAN,
	Club_Crawl BOOLEAN,
	Cocktail_Bars BOOLEAN,
	Coffee_and_Tea BOOLEAN,
	Coffee_and_Tea_Supplies BOOLEAN,
	Coffee_Roasteries BOOLEAN,
	Coffeeshops BOOLEAN,
	College_Counseling BOOLEAN,
	Colleges_and_Universities BOOLEAN,
	Colombian BOOLEAN,
	Colonics BOOLEAN,
	Comedy_Clubs BOOLEAN,
	Comfort_Food BOOLEAN,
	Comic_Books BOOLEAN,
	Commercial_Real_Estate BOOLEAN,
	Commercial_Truck_Dealers BOOLEAN,
	Commercial_Truck_Repair BOOLEAN,
	Commissioned_Artists BOOLEAN,
	Community_Centers BOOLEAN,
	Community_Gardens BOOLEAN,
	Community_Service_Non_Profit BOOLEAN,
	Computers BOOLEAN,
	Concept_Shops BOOLEAN,
	Concierge_Medicine BOOLEAN,
	Condominiums BOOLEAN,
	Congee BOOLEAN,
	Consumer_Law BOOLEAN,
	Contract_Law BOOLEAN,
	Contractors BOOLEAN,
	Convenience_Stores BOOLEAN,
	Conveyor_Belt_Sushi BOOLEAN,
	Cooking_Classes BOOLEAN,
	Cooking_Schools BOOLEAN,
	Cosmetic_Dentists BOOLEAN,
	Cosmetic_Surgeons BOOLEAN,
	Cosmetics_and_Beauty_Supply BOOLEAN,
	Cosmetology_Schools BOOLEAN,
	Costumes BOOLEAN,
	Counseling_and_Mental_Health BOOLEAN,
	Countertop_Installation BOOLEAN,
	Country_Clubs BOOLEAN,
	Country_Dance_Halls BOOLEAN,
	Couriers_and_Delivery_Services BOOLEAN,
	Court_Reporters BOOLEAN,
	Courthouses BOOLEAN,
	Crane_Services BOOLEAN,
	Cremation_Services BOOLEAN,
	Creperies BOOLEAN,
	Criminal_Defense_Law BOOLEAN,
	Crisis_Pregnancy_Centers BOOLEAN,
	Cryotherapy BOOLEAN,
	Cuban BOOLEAN,
	Cultural_Center BOOLEAN,
	Cupcakes BOOLEAN,
	Currency_Exchange BOOLEAN,
	Custom_Cakes BOOLEAN,
	Customized_Merchandise BOOLEAN,
	Cycling_Classes BOOLEAN,
	Czech BOOLEAN,
	Czech_Slovakian BOOLEAN,
	DIY_Auto_Shop BOOLEAN,
	DJs BOOLEAN,
	DUI_Law BOOLEAN,
	DUI_Schools BOOLEAN,
	Damage_Restoration BOOLEAN,
	Dance_Clubs BOOLEAN,
	Dance_Restaurants BOOLEAN,
	Dance_Schools BOOLEAN,
	Dance_Studios BOOLEAN,
	Dance_Wear BOOLEAN,
	Data_Recovery BOOLEAN,
	Day_Camps BOOLEAN,
	Day_Spas BOOLEAN,
	Debt_Relief_Services BOOLEAN,
	Decks_and_Railing BOOLEAN,
	Delicatessen BOOLEAN,
	Delis BOOLEAN,
	Demolition_Services BOOLEAN,
	Dental_Hygienists BOOLEAN,
	Dentists BOOLEAN,
	Department_Stores BOOLEAN,
	Departments_of_Motor_Vehicles BOOLEAN,
	Dermatologists BOOLEAN,
	Desserts BOOLEAN,
	Diagnostic_Imaging BOOLEAN,
	Diagnostic_Services BOOLEAN,
	Diamond_Buyers BOOLEAN,
	Dietitians BOOLEAN,
	Digitizing_Services BOOLEAN,
	Dim_Sum BOOLEAN,
	Diners BOOLEAN,
	Dinner_Theater BOOLEAN,
	Disability_Law BOOLEAN,
	Disc_Golf BOOLEAN,
	Discount_Store BOOLEAN,
	Distilleries BOOLEAN,
	Dive_Bars BOOLEAN,
	Dive_Shops BOOLEAN,
	Diving BOOLEAN,
	Divorce_and_Family_Law BOOLEAN,
	Do_It_Yourself_Food BOOLEAN,
	Doctors BOOLEAN,
	Dog_Parks BOOLEAN,
	Dog_Walkers BOOLEAN,
	Dominican BOOLEAN,
	Donairs BOOLEAN,
	Donation_Center BOOLEAN,
	Donuts BOOLEAN,
	Door_Sales_Installation BOOLEAN,
	Doulas BOOLEAN,
	Drama_Schools BOOLEAN,
	Drive_In_Theater BOOLEAN,
	Drive_Thru_Bars BOOLEAN,
	Driving_Schools BOOLEAN,
	Drones BOOLEAN,
	Drugstores BOOLEAN,
	Dry_Cleaning BOOLEAN,
	Dry_Cleaning_and_Laundry BOOLEAN,
	Drywall_Installation_and_Repair BOOLEAN,
	Dumplings BOOLEAN,
	Dumpster_Rental BOOLEAN,
	Duplication_Services BOOLEAN,
	Duty_Free_Shops BOOLEAN,
	EV_Charging_Stations BOOLEAN,
	Ear_Nose_and_Throat BOOLEAN,
	Eatertainment BOOLEAN,
	Editorial_Services BOOLEAN,
	Education BOOLEAN,
	Educational_Services BOOLEAN,
	Egyptian BOOLEAN,
	Elder_Care_Planning BOOLEAN,
	Elder_Law BOOLEAN,
	Electricians BOOLEAN,
	Electricity_Suppliers BOOLEAN,
	Electronics BOOLEAN,
	Electronics_Repair BOOLEAN,
	Elementary_Schools BOOLEAN,
	Embassy BOOLEAN,
	Embroidery_and_Crochet BOOLEAN,
	Emergency_Medicine BOOLEAN,
	Emergency_Pet_Hospital BOOLEAN,
	Emergency_Rooms BOOLEAN,
	Empanadas BOOLEAN,
	Employment_Agencies BOOLEAN,
	Employment_Law BOOLEAN,
	Endocrinologists BOOLEAN,
	Endodontists BOOLEAN,
	Engraving BOOLEAN,
	Entertainment_Law BOOLEAN,
	Environmental_Abatement BOOLEAN,
	Environmental_Testing BOOLEAN,
	Eritrean BOOLEAN,
	Escape_Games BOOLEAN,
	Estate_Liquidation BOOLEAN,
	Estate_Planning_Law BOOLEAN,
	Estheticians BOOLEAN,
	Ethical_Grocery BOOLEAN,
	Ethiopian BOOLEAN,
	Ethnic_Food BOOLEAN,
	Ethnic_Grocery BOOLEAN,
	Event_Photography BOOLEAN,
	Event_Planning_and_Services BOOLEAN,
	Excavation_Services BOOLEAN,
	Eyebrow_Services BOOLEAN,
	Eyelash_Service BOOLEAN,
	Eyewear_and_Opticians BOOLEAN,
	Fabric_Stores BOOLEAN,
	Face_Painting BOOLEAN,
	Faith_based_Crisis_Pregnancy_Centers BOOLEAN,
	Falafel BOOLEAN,
	Family_Practice BOOLEAN,
	Farm_Equipment_Repair BOOLEAN,
	Farmers_Market BOOLEAN,
	Farming_Equipment BOOLEAN,
	Farms BOOLEAN,
	Fashion BOOLEAN,
	Fast_Food BOOLEAN,
	Fences_and_Gates BOOLEAN,
	Fencing_Clubs BOOLEAN,
	Feng_Shui BOOLEAN,
	Ferries BOOLEAN,
	Fertility BOOLEAN,
	Festivals BOOLEAN,
	Filipino BOOLEAN,
	Financial_Advising BOOLEAN,
	Financial_Services BOOLEAN,
	Fingerprinting BOOLEAN,
	Fire_Departments BOOLEAN,
	Fire_Protection_Services BOOLEAN,
	Firearm_Training BOOLEAN,
	Fireplace_Services BOOLEAN,
	Firewood BOOLEAN,
	Fireworks BOOLEAN,
	First_Aid_Classes BOOLEAN,
	Fischbroetchen BOOLEAN,
	Fish_and_Chips BOOLEAN,
	Fishing BOOLEAN,
	Fishmonger BOOLEAN,
	Fitness_and_Instruction BOOLEAN,
	Fitness_Exercise_Equipment BOOLEAN,
	Flea_Markets BOOLEAN,
	Flight_Instruction BOOLEAN,
	Float_Spa BOOLEAN,
	Flooring BOOLEAN,
	Floral_Designers BOOLEAN,
	Florists BOOLEAN,
	Flowers BOOLEAN,
	Flowers_and_Gifts BOOLEAN,
	Flyboarding BOOLEAN,
	Fondue BOOLEAN,
	Food BOOLEAN,
	Food_Banks BOOLEAN,
	Food_Court BOOLEAN,
	Food_Delivery_Services BOOLEAN,
	Food_Safety_Training BOOLEAN,
	Food_Stands BOOLEAN,
	Food_Tours BOOLEAN,
	Food_Trucks BOOLEAN,
	Foot_Care BOOLEAN,
	Formal_Wear BOOLEAN,
	Foundation_Repair BOOLEAN,
	Framing BOOLEAN,
	Free_Diving BOOLEAN,
	French BOOLEAN,
	French_Southwest BOOLEAN,
	Fruits_and_Veggies BOOLEAN,
	Fuel_Docks BOOLEAN,
	Fun_Fair BOOLEAN,
	Funeral_Services_and_Cemeteries BOOLEAN,
	Fur_Clothing BOOLEAN,
	Furniture_Assembly BOOLEAN,
	Furniture_Rental BOOLEAN,
	Furniture_Repair BOOLEAN,
	Furniture_Reupholstery BOOLEAN,
	Furniture_Stores BOOLEAN,
	Game_Truck_Rental BOOLEAN,
	Garage_Door_Services BOOLEAN,
	Gardeners BOOLEAN,
	Gas_Stations BOOLEAN,
	Gastroenterologist BOOLEAN,
	Gastropubs BOOLEAN,
	Gay_Bars BOOLEAN,
	Gelato BOOLEAN,
	Gemstones_and_Minerals BOOLEAN,
	General_Dentistry BOOLEAN,
	General_Litigation BOOLEAN,
	Generator_Installation_Repair BOOLEAN,
	Geneticists BOOLEAN,
	Georgian BOOLEAN,
	German BOOLEAN,
	Gerontologists BOOLEAN,
	Gift_Shops BOOLEAN,
	Glass_and_Mirrors BOOLEAN,
	Glass_Blowing BOOLEAN,
	Gluten_Free BOOLEAN,
	Go_Karts BOOLEAN,
	Gold_Buyers BOOLEAN,
	Golf BOOLEAN,
	Golf_Cart_Dealers BOOLEAN,
	Golf_Cart_Rentals BOOLEAN,
	Golf_Equipment BOOLEAN,
	Golf_Equipment_Shops BOOLEAN,
	Golf_Lessons BOOLEAN,
	Graphic_Design BOOLEAN,
	Greek BOOLEAN,
	Grill_Services BOOLEAN,
	Grilling_Equipment BOOLEAN,
	Grocery BOOLEAN,
	Grout_Services BOOLEAN,
	Guamanian BOOLEAN,
	Guest_Houses BOOLEAN,
	Guitar_Stores BOOLEAN,
	Gun_Rifle_Ranges BOOLEAN,
	Guns_and_Ammo BOOLEAN,
	Gunsmith BOOLEAN,
	Gutter_Services BOOLEAN,
	Gymnastics BOOLEAN,
	Gyms BOOLEAN,
	Hair_Extensions BOOLEAN,
	Hair_Loss_Centers BOOLEAN,
	Hair_Removal BOOLEAN,
	Hair_Salons BOOLEAN,
	Hair_Stylists BOOLEAN,
	Haitian BOOLEAN,
	Hakka BOOLEAN,
	Halal BOOLEAN,
	Halotherapy BOOLEAN,
	Hand_Rolls BOOLEAN,
	Handyman BOOLEAN,
	Hang_Gliding BOOLEAN,
	Hardware_Stores BOOLEAN,
	Hats BOOLEAN,
	Haunted_Houses BOOLEAN,
	Hawaiian BOOLEAN,
	Hazardous_Waste_Disposal BOOLEAN,
	Head_Shops BOOLEAN,
	Health_and_Medical BOOLEAN,
	Health_Coach BOOLEAN,
	Health_Insurance_Offices BOOLEAN,
	Health_Markets BOOLEAN,
	Health_Retreats BOOLEAN,
	Hearing_Aid_Providers BOOLEAN,
	Hearing_Aids BOOLEAN,
	Heating_and_Air_Conditioning_HVAC BOOLEAN,
	Henna_Artists BOOLEAN,
	Hepatologists BOOLEAN,
	Herbal_Shops BOOLEAN,
	Herbs_and_Spices BOOLEAN,
	High_Fidelity_Audio_Equipment BOOLEAN,
	Hiking BOOLEAN,
	Himalayan_Nepalese BOOLEAN,
	Hindu_Temples BOOLEAN,
	Historical_Tours BOOLEAN,
	Hobby_Shops BOOLEAN,
	Hockey_Equipment BOOLEAN,
	Holiday_Decorating_Services BOOLEAN,
	Holiday_Decorations BOOLEAN,
	Holistic_Animal_Care BOOLEAN,
	Home_and_Garden BOOLEAN,
	Home_and_Rental_Insurance BOOLEAN,
	Home_Automation BOOLEAN,
	Home_Cleaning BOOLEAN,
	Home_Decor BOOLEAN,
	Home_Developers BOOLEAN,
	Home_Energy_Auditors BOOLEAN,
	Home_Health_Care BOOLEAN,
	Home_Inspectors BOOLEAN,
	Home_Network_Installation BOOLEAN,
	Home_Organization BOOLEAN,
	Home_Services BOOLEAN,
	Home_Staging BOOLEAN,
	Home_Theatre_Installation BOOLEAN,
	Home_Window_Tinting BOOLEAN,
	Homeless_Shelters BOOLEAN,
	Homeowner_Association BOOLEAN,
	Honduran BOOLEAN,
	Honey BOOLEAN,
	Hong_Kong_Style_Cafe BOOLEAN,
	Hookah_Bars BOOLEAN,
	Horse_Boarding BOOLEAN,
	Horse_Equipment_Shops BOOLEAN,
	Horse_Racing BOOLEAN,
	Horseback_Riding BOOLEAN,
	Hospice BOOLEAN,
	Hospitals BOOLEAN,
	Hostels BOOLEAN,
	Hot_Air_Balloons BOOLEAN,
	Hot_Dogs BOOLEAN,
	Hot_Pot BOOLEAN,
	Hot_Springs BOOLEAN,
	Hot_Tub_and_Pool BOOLEAN,
	Hotel_bar BOOLEAN,
	Hotels BOOLEAN,
	Hotels_and_Travel BOOLEAN,
	House_Sitters BOOLEAN,
	Housing_Cooperatives BOOLEAN,
	Hungarian BOOLEAN,
	Hunting_and_Fishing_Supplies BOOLEAN,
	Hybrid_Car_Repair BOOLEAN,
	Hydro_jetting BOOLEAN,
	Hydroponics BOOLEAN,
	Hydrotherapy BOOLEAN,
	Hypnosis_Hypnotherapy BOOLEAN,
	IP_and_Internet_Law BOOLEAN,
	IT_Services_and_Computer_Repair BOOLEAN,
	IV_Hydration BOOLEAN,
	Iberian BOOLEAN,
	Ice_Cream_and_Frozen_Yogurt BOOLEAN,
	Ice_Delivery BOOLEAN,
	Immigration_Law BOOLEAN,
	Immunodermatologists BOOLEAN,
	Imported_Food BOOLEAN,
	Indian BOOLEAN,
	Indonesian BOOLEAN,
	Indoor_Landscaping BOOLEAN,
	Indoor_Playcentre BOOLEAN,
	Infectious_Disease_Specialists BOOLEAN,
	Installment_Loans BOOLEAN,
	Insulation_Installation BOOLEAN,
	Insurance BOOLEAN,
	Interior_Design BOOLEAN,
	Interlock_Systems BOOLEAN,
	Internal_Medicine BOOLEAN,
	International BOOLEAN,
	International_Grocery BOOLEAN,
	Internet_Cafes BOOLEAN,
	Internet_Service_Providers BOOLEAN,
	Interval_Training_Gyms BOOLEAN,
	Investing BOOLEAN,
	Irish BOOLEAN,
	Irish_Pub BOOLEAN,
	Irrigation BOOLEAN,
	Italian BOOLEAN,
	Izakaya BOOLEAN,
	Jails_and_Prisons BOOLEAN,
	Japanese BOOLEAN,
	Japanese_Curry BOOLEAN,
	Jazz_and_Blues BOOLEAN,
	Jet_Skis BOOLEAN,
	Jewelry BOOLEAN,
	Jewelry_Repair BOOLEAN,
	Jewish BOOLEAN,
	Juice_Bars_and_Smoothies BOOLEAN,
	Junk_Removal_and_Hauling BOOLEAN,
	Junkyards BOOLEAN,
	Karaoke BOOLEAN,
	Karaoke_Rental BOOLEAN,
	Karate BOOLEAN,
	Kebab BOOLEAN,
	Keys_and_Locksmiths BOOLEAN,
	Kickboxing BOOLEAN,
	Kids_Activities BOOLEAN,
	Kids_Hair_Salons BOOLEAN,
	Kiosk BOOLEAN,
	Kitchen_and_Bath BOOLEAN,
	Kitchen_Incubators BOOLEAN,
	Kitchen_Supplies BOOLEAN,
	Kiteboarding BOOLEAN,
	Knife_Sharpening BOOLEAN,
	Knitting_Supplies BOOLEAN,
	Kombucha BOOLEAN,
	Korean BOOLEAN,
	Kosher BOOLEAN,
	LAN_Centers BOOLEAN,
	Laboratory_Testing BOOLEAN,
	Lactation_Services BOOLEAN,
	Lakes BOOLEAN,
	Land_Surveying BOOLEAN,
	Landmarks_and_Historical_Buildings BOOLEAN,
	Landscape_Architects BOOLEAN,
	Landscaping BOOLEAN,
	Language_Schools BOOLEAN,
	Laotian BOOLEAN,
	Laser_Eye_Surgery_Lasik BOOLEAN,
	Laser_Hair_Removal BOOLEAN,
	Laser_Tag BOOLEAN,
	Latin_American BOOLEAN,
	Laundromat BOOLEAN,
	Laundry_Services BOOLEAN,
	Lawn_Services BOOLEAN,
	Lawyers BOOLEAN,
	Leather_Goods BOOLEAN,
	Lebanese BOOLEAN,
	Legal_Services BOOLEAN,
	Leisure_Centers BOOLEAN,
	Libraries BOOLEAN,
	Lice_Services BOOLEAN,
	Life_Coach BOOLEAN,
	Life_Insurance BOOLEAN,
	Lighting_Fixtures_and_Equipment BOOLEAN,
	Lighting_Stores BOOLEAN,
	Limos BOOLEAN,
	Lingerie BOOLEAN,
	Live_Raw_Food BOOLEAN,
	Livestock_Feed_and_Supply BOOLEAN,
	Local_Fish_Stores BOOLEAN,
	Local_Flavor BOOLEAN,
	Local_Services BOOLEAN,
	Lounges BOOLEAN,
	Luggage BOOLEAN,
	Luggage_Storage BOOLEAN,
	Macarons BOOLEAN,
	Machine_and_Tool_Rental BOOLEAN,
	Machine_Shops BOOLEAN,
	Magicians BOOLEAN,
	Mags BOOLEAN,
	Mailbox_Centers BOOLEAN,
	Makerspaces BOOLEAN,
	Makeup_Artists BOOLEAN,
	Malaysian BOOLEAN,
	Marinas BOOLEAN,
	Marketing BOOLEAN,
	Martial_Arts BOOLEAN,
	Masonry_Concrete BOOLEAN,
	Mass_Media BOOLEAN,
	Massage BOOLEAN,
	Massage_Schools BOOLEAN,
	Massage_Therapy BOOLEAN,
	Matchmakers BOOLEAN,
	Maternity_Wear BOOLEAN,
	Mattresses BOOLEAN,
	Mauritius BOOLEAN,
	Meaderies BOOLEAN,
	Meat_Shops BOOLEAN,
	Mediators BOOLEAN,
	Medical_Cannabis_Referrals BOOLEAN,
	Medical_Centers BOOLEAN,
	Medical_Foot_Care BOOLEAN,
	Medical_Law BOOLEAN,
	Medical_Spas BOOLEAN,
	Medical_Supplies BOOLEAN,
	Medical_Transportation BOOLEAN,
	Meditation_Centers BOOLEAN,
	Mediterranean BOOLEAN,
	Memory_Care BOOLEAN,
	Mens_Clothing BOOLEAN,
	Mens_Hair_Salons BOOLEAN,
	Metal_Detector_Services BOOLEAN,
	Metal_Fabricators BOOLEAN,
	Metro_Stations BOOLEAN,
	Mexican BOOLEAN,
	Middle_Eastern BOOLEAN,
	Middle_Schools_and_High_Schools BOOLEAN,
	Midwives BOOLEAN,
	Military_Surplus BOOLEAN,
	Mini_Golf BOOLEAN,
	Mobile_Dent_Repair BOOLEAN,
	Mobile_Home_Dealers BOOLEAN,
	Mobile_Home_Parks BOOLEAN,
	Mobile_Home_Repair BOOLEAN,
	Mobile_Phone_Accessories BOOLEAN,
	Mobile_Phone_Repair BOOLEAN,
	Mobile_Phones BOOLEAN,
	Mobility_Equipment_Sales_and_Services BOOLEAN,
	Modern_European BOOLEAN,
	Mohels BOOLEAN,
	Mongolian BOOLEAN,
	Montessori_Schools BOOLEAN,
	Moroccan BOOLEAN,
	Mortgage_Brokers BOOLEAN,
	Mortgage_Lenders BOOLEAN,
	Mortuary_Services BOOLEAN,
	Mosques BOOLEAN,
	Motorcycle_Dealers BOOLEAN,
	Motorcycle_Gear BOOLEAN,
	Motorcycle_Parts_and_Supplies BOOLEAN,
	Motorcycle_Rental BOOLEAN,
	Motorcycle_Repair BOOLEAN,
	Motorsport_Vehicle_Dealers BOOLEAN,
	Motorsport_Vehicle_Repairs BOOLEAN,
	Mountain_Biking BOOLEAN,
	Movers BOOLEAN,
	Muay_Thai BOOLEAN,
	Municipality BOOLEAN,
	Museums BOOLEAN,
	Music_and_DVDs BOOLEAN,
	Music_and_Video BOOLEAN,
	Music_Production_Services BOOLEAN,
	Music_Venues BOOLEAN,
	Musical_Instrument_Services BOOLEAN,
	Musical_Instruments_and_Teachers BOOLEAN,
	Musicians BOOLEAN,
	Mystics BOOLEAN,
	Nail_Salons BOOLEAN,
	Nail_Technicians BOOLEAN,
	Nanny_Services BOOLEAN,
	Napoletana BOOLEAN,
	Natural_Gas_Suppliers BOOLEAN,
	Naturopathic_Holistic BOOLEAN,
	Nephrologists BOOLEAN,
	Neurologist BOOLEAN,
	Neuropathologists BOOLEAN,
	Neurotologists BOOLEAN,
	New_Mexican_Cuisine BOOLEAN,
	Newspapers_and_Magazines BOOLEAN,
	Nicaraguan BOOLEAN,
	Nightlife BOOLEAN,
	Noodles BOOLEAN,
	Notaries BOOLEAN,
	Nudist BOOLEAN,
	Nurse_Practitioner BOOLEAN,
	Nurseries_and_Gardening BOOLEAN,
	Nursing_Schools BOOLEAN,
	Nutritionists BOOLEAN,
	Oaxacan BOOLEAN,
	Observatories BOOLEAN,
	Obstetricians_and_Gynecologists BOOLEAN,
	Occupational_Therapy BOOLEAN,
	Office_Cleaning BOOLEAN,
	Office_Equipment BOOLEAN,
	Officiants BOOLEAN,
	Oil_Change_Stations BOOLEAN,
	Olive_Oil BOOLEAN,
	Oncologist BOOLEAN,
	Opera_and_Ballet BOOLEAN,
	Ophthalmologists BOOLEAN,
	Optometrists BOOLEAN,
	Oral_Surgeons BOOLEAN,
	Organic_Stores BOOLEAN,
	Oriental BOOLEAN,
	Orthodontists BOOLEAN,
	Orthopedists BOOLEAN,
	Orthotics BOOLEAN,
	Osteopathic_Physicians BOOLEAN,
	Otologists BOOLEAN,
	Outdoor_Furniture_Stores BOOLEAN,
	Outdoor_Gear BOOLEAN,
	Outdoor_Movies BOOLEAN,
	Outdoor_Power_Equipment_Services BOOLEAN,
	Outlet_Stores BOOLEAN,
	Oxygen_Bars BOOLEAN,
	Packing_Services BOOLEAN,
	Packing_Supplies BOOLEAN,
	Paddleboarding BOOLEAN,
	Pain_Management BOOLEAN,
	Paint_and_Sip BOOLEAN,
	Paint_Stores BOOLEAN,
	Paint_Your_Own_Pottery BOOLEAN,
	Paintball BOOLEAN,
	Painters BOOLEAN,
	Pakistani BOOLEAN,
	Pan_Asian BOOLEAN,
	Pancakes BOOLEAN,
	Paragliding BOOLEAN,
	Parent_Cafes BOOLEAN,
	Parenting_Classes BOOLEAN,
	Parking BOOLEAN,
	Parklets BOOLEAN,
	Parks BOOLEAN,
	Party_and_Event_Planning BOOLEAN,
	Party_Bike_Rentals BOOLEAN,
	Party_Bus_Rentals BOOLEAN,
	Party_Characters BOOLEAN,
	Party_Equipment_Rentals BOOLEAN,
	Party_Supplies BOOLEAN,
	Passport_and_Visa_Services BOOLEAN,
	Pasta_Shops BOOLEAN,
	Patent_Law BOOLEAN,
	Pathologists BOOLEAN,
	Patio_Coverings BOOLEAN,
	Patisserie_Cake_Shop BOOLEAN,
	Pawn_Shops BOOLEAN,
	Payroll_Services BOOLEAN,
	Pediatric_Dentists BOOLEAN,
	Pediatricians BOOLEAN,
	Pedicabs BOOLEAN,
	Performing_Arts BOOLEAN,
	Perfume BOOLEAN,
	Periodontists BOOLEAN,
	Permanent_Makeup BOOLEAN,
	Persian_Iranian BOOLEAN,
	Personal_Assistants BOOLEAN,
	Personal_Care_Services BOOLEAN,
	Personal_Chefs BOOLEAN,
	Personal_Injury_Law BOOLEAN,
	Personal_Shopping BOOLEAN,
	Peruvian BOOLEAN,
	Pest_Control BOOLEAN,
	Pet_Adoption BOOLEAN,
	Pet_Boarding BOOLEAN,
	Pet_Breeders BOOLEAN,
	Pet_Cremation_Services BOOLEAN,
	Pet_Groomers BOOLEAN,
	Pet_Hospice BOOLEAN,
	Pet_Insurance BOOLEAN,
	Pet_Photography BOOLEAN,
	Pet_Services BOOLEAN,
	Pet_Sitting BOOLEAN,
	Pet_Stores BOOLEAN,
	Pet_Training BOOLEAN,
	Pet_Transportation BOOLEAN,
	Pet_Waste_Removal BOOLEAN,
	Pets BOOLEAN,
	Petting_Zoos BOOLEAN,
	Pharmacy BOOLEAN,
	Phlebologists BOOLEAN,
	Photo_Booth_Rentals BOOLEAN,
	Photographers BOOLEAN,
	Photography_Classes BOOLEAN,
	Photography_Stores_and_Services BOOLEAN,
	Physical_Therapy BOOLEAN,
	Piadina BOOLEAN,
	Piano_Bars BOOLEAN,
	Piano_Services BOOLEAN,
	Piano_Stores BOOLEAN,
	Pick_Your_Own_Farms BOOLEAN,
	Pickleball BOOLEAN,
	Piercing BOOLEAN,
	Pilates BOOLEAN,
	Pita BOOLEAN,
	Pizza BOOLEAN,
	Placenta_Encapsulations BOOLEAN,
	Planetarium BOOLEAN,
	Plastic_Surgeons BOOLEAN,
	Playgrounds BOOLEAN,
	Playsets BOOLEAN,
	Plumbing BOOLEAN,
	Plus_Size_Fashion BOOLEAN,
	Podiatrists BOOLEAN,
	Poke BOOLEAN,
	Pole_Dancing_Classes BOOLEAN,
	Police_Departments BOOLEAN,
	Polish BOOLEAN,
	Polynesian BOOLEAN,
	Pool_and_Billiards BOOLEAN,
	Pool_and_Hot_Tub_Service BOOLEAN,
	Pool_Cleaners BOOLEAN,
	Pool_Halls BOOLEAN,
	Pop_Up_Restaurants BOOLEAN,
	Pop_up_Shops BOOLEAN,
	Popcorn_Shops BOOLEAN,
	Portable_Toilet_Services BOOLEAN,
	Portuguese BOOLEAN,
	Post_Offices BOOLEAN,
	Poutineries BOOLEAN,
	Powder_Coating BOOLEAN,
	Prenatal_Perinatal_Care BOOLEAN,
	Preschools BOOLEAN,
	Pressure_Washers BOOLEAN,
	Pretzels BOOLEAN,
	Preventive_Medicine BOOLEAN,
	Print_Media BOOLEAN,
	Printing_Services BOOLEAN,
	Private_Investigation BOOLEAN,
	Private_Jet_Charter BOOLEAN,
	Private_Schools BOOLEAN,
	Private_Tutors BOOLEAN,
	Process_Servers BOOLEAN,
	Proctologists BOOLEAN,
	Product_Design BOOLEAN,
	Professional_Services BOOLEAN,
	Professional_Sports_Teams BOOLEAN,
	Propane BOOLEAN,
	Property_Management BOOLEAN,
	Props BOOLEAN,
	Prosthetics BOOLEAN,
	Prosthodontists BOOLEAN,
	Psychiatrists BOOLEAN,
	Psychic_Mediums BOOLEAN,
	Psychics BOOLEAN,
	Psychologists BOOLEAN,
	Pub_Food BOOLEAN
);